fix: enhance badge addition process with error handling and notifications

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -263,31 +263,47 @@ runs:
           exit 0
         fi
 
-        echo "::debug file=action.yml,line=217::Adding ${{ inputs.badge-directory }}/pylint.svg"
+        echo "::debug file=action.yml,line=267::Adding ${{ inputs.badge-directory }}/pylint.svg"
         git add "${{ inputs.badge-directory }}/pylint.svg"
+        if [ $? -ne 0 ]; then
+          echo "::warning file=action.yml,line=268::Failed to add pylint badge. Directory may not exist."
+        fi
         
-        echo "::debug file=action.yml,line=218::Adding ${{ inputs.badge-directory }}/black.svg"
+        echo "::debug file=action.yml,line=270::Adding ${{ inputs.badge-directory }}/black.svg"
         git add "${{ inputs.badge-directory }}/black.svg"
+        if [ $? -ne 0 ]; then
+          echo "::warning file=action.yml,line=271::Failed to add black badge. Directory may not exist."
+        fi
         
-        echo "::debug file=action.yml,line=219::Adding ${{ inputs.badge-directory }}/mypy.svg"
+        echo "::debug file=action.yml,line=273::Adding ${{ inputs.badge-directory }}/mypy.svg"
         git add "${{ inputs.badge-directory }}/mypy.svg"
+        if [ $? -ne 0 ]; then
+          echo "::warning file=action.yml,line=274::Failed to add mypy badge. Directory may not exist."
+        fi
         
-        echo "::notice file=action.yml,line=219::Badge files added to staging area."
-        echo "::debug file=action.yml,line=220::Checking for changes to commit."
+        echo "::notice file=action.yml,line=284::Badge files added to staging area."
+
+        echo "::debug file=action.yml,line=288::Checking for changes to commit."
         
-        if git diff --staged --quiet; then
-          echo "::notice file=action.yml,line=222::No changes to commit"
+        git diff --staged --quiet
+        
+        if [ $? -eq 0 ]; then
+          echo "::notice file=action.yml,line=277::No changes to commit."
+          exit 0
+        fi
+        echo "::notice file=action.yml,line=281::Committing and pushing badge changes to repository."
+        git commit -m "Update linting badges [skip ci]"
+
+        git push
+
+        if [ $? -eq 0 ]; then
+          echo "::notice file=action.yml,line=282::Changes committed and pushed to repository."
         else
-          echo "::notice file=action.yml,line=224::Committing and pushing badge changes to repository."
-          git commit -m "Update linting badges [skip ci]"
-          if git push; then
-            echo "::notice file=action.yml,line=227::Changes committed and pushed to repository.
-          else
-            echo "::warning file=action.yml,line=230::Failed to push changes to repository."
-            echo "::notice file=action.yml,line=231::This may be due to insufficient permissions or a merge conflict."
-            echo ""
-            exit 0
-          fi
+          echo "::warning file=action.yml,line=283::Failed to push changes to repository."
+          echo "::notice file=action.yml,line=284::This may be due to insufficient permissions or a merge conflict."
+          echo ""
+          exit 0
+        fi
       shell: bash
       if: always()
 
